//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolsSystems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolForm
    {
        public SchoolForm()
        {
            this.Pupil = new HashSet<Pupil>();
            this.TimeTable = new HashSet<TimeTable>();
        }

        public int Id { get; set; }
        public int SchoolId { get; set; }
        public int FormId { get; set; }
        public int FormLetterId { get; set; }

        public string Name
        {
            get
            {
                return string.Format("{0} {1}", FormId, FormLetter.Letter);
            }
        }
    
        public virtual Form Form { get; set; }
        public virtual FormLetter FormLetter { get; set; }
        public virtual ICollection<Pupil> Pupil { get; set; }
        public virtual School School { get; set; }
        public virtual ICollection<TimeTable> TimeTable { get; set; }
    }
}
