//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolsSystems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.Pupil = new HashSet<Pupil>();
            this.SchoolForm = new HashSet<SchoolForm>();
            this.TimeTable = new HashSet<TimeTable>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CityId { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Pupil> Pupil { get; set; }
        public virtual ICollection<SchoolForm> SchoolForm { get; set; }
        public virtual ICollection<TimeTable> TimeTable { get; set; }
    }
}
